"""Agregar campos GPS a User

Revision ID: 206aa616a3e6
Revises: 
Create Date: 2026-01-01 23:28:06.860680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '206aa616a3e6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_location_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_location_update')
        batch_op.drop_column('last_lng')
        batch_op.drop_column('last_lat')

    # ### end Alembic commands ###
